### PR TITLE
Context propagation not working in async calls 

### LINKED ISSUE #947: Context propagation not working in async calls
When using [HTTP Async Transport](https://docs.quarkiverse.io/quarkus-cxf/dev/reference/extensions/quarkus-cxf-rt-transports-http-hc5.html) context propagation is not made when using [quarkus-smallrye-context-propagation](https://quarkus.io/guides/context-propagation). This is in contrast to async REST requests, where the context is correctly propagated.

I have created a reproducer project [here](https://github.com/AndreasPetersen/quarkus-cxf-context-propagation-bug). In it, you will find a [test](https://github.com/AndreasPetersen/quarkus-cxf-context-propagation-bug/blob/main/src/test/java/org/acme/GreetingResourceTest.java) which calls an HTTP server REST endpoint, which makes a call to:

- A sync REST client
- An async REST client
- A sync SOAP client
- An async SOAP client. This test case fails.

I'm using the [Micrometer metrics](https://docs.quarkiverse.io/quarkus-cxf/dev/reference/extensions/quarkus-cxf-rt-features-metrics.html) feature with Quarkus CXF , and I've created a `MeterFilter` that adds tags to the created metrics from a `@RequestScope`d bean. However, since the no context propagation is done on the async SOAP client call, the `MeterFilter` fails with:

```
2023-08-02 13:51:09,179 WARN  [org.apa.cxf.pha.PhaseInterceptorChain] (default-workqueue-1) Exception in handleFault on interceptor org.apache.cxf.metrics.interceptors.MetricsMessageInInterceptor@6f400618: jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=org.acme.RequestScopedHeader, id=88dfd968e166472ee5433588607fd7b273d3ab8a]
	- you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:55)
	at org.acme.RequestScopedHeader_ClientProxy.arc$delegate(Unknown Source)
	at org.acme.RequestScopedHeader_ClientProxy.getHeaderValue(Unknown Source)
	at org.acme.MeterFilterProducer$1.map(MeterFilterProducer.java:22)
	at io.micrometer.core.instrument.MeterRegistry.getMappedId(MeterRegistry.java:593)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:576)
	at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:323)
	at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:444)
	at org.apache.cxf.metrics.micrometer.MicrometerMetricsContext.stop(MicrometerMetricsContext.java:124)
	at org.apache.cxf.metrics.micrometer.MicrometerMetricsContext.record(MicrometerMetricsContext.java:104)
	at org.apache.cxf.metrics.micrometer.MicrometerClientMetricsContext.record(MicrometerClientMetricsContext.java:56)
	at org.apache.cxf.metrics.micrometer.MicrometerMetricsContext.stop(MicrometerMetricsContext.java:79)
	at org.apache.cxf.metrics.micrometer.MicrometerClientMetricsContext.stop(MicrometerClientMetricsContext.java:46)
	at org.apache.cxf.metrics.ExchangeMetrics.stop(ExchangeMetrics.java:75)
	at org.apache.cxf.metrics.interceptors.AbstractMetricsInterceptor.stop(AbstractMetricsInterceptor.java:214)
	at org.apache.cxf.metrics.interceptors.MetricsMessageInInterceptor.handleFault(MetricsMessageInInterceptor.java:50)
	at org.apache.cxf.phase.PhaseInterceptorChain.unwind(PhaseInterceptorChain.java:498)
	at org.apache.cxf.phase.PhaseInterceptorChain.wrapExceptionAsFault(PhaseInterceptorChain.java:349)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:331)
	at org.apache.cxf.endpoint.ClientImpl.onMessage(ClientImpl.java:808)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1738)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream$1.run(HTTPConduit.java:1216)
	at org.apache.cxf.workqueue.AutomaticWorkQueueImpl$3.run(AutomaticWorkQueueImpl.java:413)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.apache.cxf.workqueue.AutomaticWorkQueueImpl$AWQThreadFactory$1.run(AutomaticWorkQueueImpl.java:346)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by ppalaga**
fix #947

### CODE REVIEW

**Comment by ppalaga** [comment]
@dufoli @shumonsharif @ffang this feels like quite a colossal hack. The idea is to intercept the creation of `CXFHttpAsyncResponseConsumer` around here https://github.com/apache/cxf/blob/cxf-4.0.2/rt/transports/http-hc5/src/main/java/org/apache/cxf/transport/http/asyncclient/hc5/AsyncHTTPConduit.java#L619-L623 and wrap it in `ThreadContext.contextualRunnable` to store the context for use in the thread executing the response consumer. I have basically done it by overridding HC5 client's  doExecute() here: https://github.com/quarkiverse/quarkus-cxf/pull/950/files#diff-568a3d75d004f9f41c6130854755ebb2beae2f30308cc45aa98492d09bac2eccR126
Do you perhaps see a more elegant way to do it using means available in CXF? If not, do you think it would be feasible to provide some new API that would allow this?

**Comment by ppalaga** [comment]
311741c: added a test to make sure that the clients still work also when the request context is not set.

**Comment by ppalaga** [comment]
I have filed a followup and will merge this PR as is.

File: extensions/transports-http-hc5/runtime/src/main/java/io/quarkiverse/cxf/transport/http/hc5/QuarkusWorkQueueImpl.java [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+            managedExecutor.execute(r);
+        } else {
+            throw new IllegalStateException(ManagedExecutor.class.getName() + " not available in Arc");
+        }
+    }
+
+    @Override
+    public void execute(Runnable work, long timeout) {
+        execute(work);
+    }
```
[the remark this answers is not in the document]
Comment (FroMage) [reply extensions/transports-http-hc5/runtime/src/main/java/io/quarkiverse/cxf/transport/http/hc5/QuarkusWorkQueueImpl.java:52]: Hum. Not sure, no.

File: extensions/transports-http-hc5/runtime/src/main/java/io/quarkiverse/cxf/transport/http/hc5/QuarkusWorkQueueImpl.java [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+                } finally {
+                    if (orig != null) {
+                        orig.reset();
+                    }
+                }
+            }
+        };
+        InstanceHandle<ManagedExecutor> managedExecutorInst = Arc.container().instance(ManagedExecutor.class);
+        if (managedExecutorInst.isAvailable()) {
+            ManagedExecutor managedExecutor = managedExecutorInst.get();
```
Comment (ppalaga) [inline extensions/transports-http-hc5/runtime/src/main/java/io/quarkiverse/cxf/transport/http/hc5/QuarkusWorkQueueImpl.java:42]: @FroMage, one more question: I thought this would give me some global ManagedExecutor managed by Quarkus and configured using some standard Quarkus properties. But the more I read the [context propagations guide](https://quarkus.io/guides/context-propagation), the more it sounds like I would get a new instance every time I call `Arc.container().instance(ManagedExecutor.class)` - is that correct?

Comment (FroMage) [reply extensions/transports-http-hc5/runtime/src/main/java/io/quarkiverse/cxf/transport/http/hc5/QuarkusWorkQueueImpl.java:42]: In the context of Quarkus, you will get the Quarkus executor. At least that's the theory ;)

Comment (ppalaga) [reply extensions/transports-http-hc5/runtime/src/main/java/io/quarkiverse/cxf/transport/http/hc5/QuarkusWorkQueueImpl.java:42]: Would that be the one configured through the quarkus.thread-pool.* set of options? https://quarkus.io/guides/all-config#quarkus-core_quarkus.thread-pool.core-threads

Comment (FroMage) [reply extensions/transports-http-hc5/runtime/src/main/java/io/quarkiverse/cxf/transport/http/hc5/QuarkusWorkQueueImpl.java:42]: Yes.

Comment (FroMage) [reply extensions/transports-http-hc5/runtime/src/main/java/io/quarkiverse/cxf/transport/http/hc5/QuarkusWorkQueueImpl.java:42]: Yes.

Comment (ppalaga) [reply extensions/transports-http-hc5/runtime/src/main/java/io/quarkiverse/cxf/transport/http/hc5/QuarkusWorkQueueImpl.java:42]: Perfect, thanks a lot! I have adapted our docs: https://github.com/quarkiverse/quarkus-cxf/pull/957

**Comment by dufoli** [comment]
Sorry, I have take a look to it but I do not see any solution except the one you have done.

Bus have 2 extensions : 
- AsyncHTTPConduitFactory (HTTPConduitFactory)
- AsyncHttpTransportFactory (ConduitInitiator)
and another one bus extension is HTTPConduitConfigurer

I do not find anyway to setup a configurer or any other way to catch the chain of call...

**Comment by dufoli** [comment]
other option is maybe to use vertx async and do our own version of conduit/ transport without hc5...

**Comment by ppalaga** [comment]
> use vertx async and do our own version of conduit/ transport without hc5

Sounds interesting

**Comment by ppalaga** [comment]
> Sorry, I have take a look to it but I do not see any solution except the one you have done.
> 
> Bus have 2 extensions :
> 
> * AsyncHTTPConduitFactory (HTTPConduitFactory)
> * AsyncHttpTransportFactory (ConduitInitiator)
>   and another one bus extension is HTTPConduitConfigurer
> 
> I do not find anyway to setup a configurer or any other way to catch the chain of call...

Would you by any chance be able to propose an enhancement of CXF API via https://issues.apache.org/jira/browse/CXF-8911 %

**Comment by dufoli** [comment]
I am not an expert. I have only worked on code generation for quarkus cxf ;-) But yes we need something a way to inject the context in chain and reta seems to want it in responseCallback. I have propose 2 API for that. Let s see, if he have a better idea.
