### PR TITLE
Fix invalid import URLs in WSDLs

### LINKED ISSUE #323: Invalid URL generated in XML "import"
Starting from 0.10.0, when publishing a webservice with the _targetNamespace_ attribute of the `@WebService` annotation, XML schema is not embedded within the WSDL but linked via _import_; the problem is that the _import_ statement contains an invalid URL, such as this one:
`<wsdl:import location="http://localhost:8080/soap/test?wsdl?wsdl=TestService.wsdl" namespace="mynamespace"> </wsdl:import>`

Workarounds:
- Don't specify a targetNamespace (but some services may need it);
- Include a pre-generated WSDL (but the WSDL file would need to be manually edited whenever a field is added to the model, for example);
- Specify a _quarkus.cxf.endpoint.key.published-endpoint-url_ property (not optimal because different environments would need different configurations; in most use cases auto-detection of the published URL is desirable).

Example mini-project to reproduce: [cxftest.zip](https://github.com/quarkiverse/quarkus-cxf/files/7642790/cxftest.zip)

### PR DESCRIPTION
**Pull request by shumonsharif**
Fixes #323 and #345.

@famod Please have a quick review.  The core issue was that `getRequestURL()` was returning the URL with query parameters in it; it should have been without.  This was a tricky one to figure out.

This not only fixes the issues with the XSD imports, but also the service address location should appear correctly in the WSDLs now, as shown below, without any query parameters (eg. ?wsdl) in it.

```xml
<wsdl:service name="CxftestSoapService">
    <wsdl:port binding="tns:CxftestSoapBinding" name="CxftestServicePort">
        <soap:address location="http://localhost:8080/soap/CxftestSoapService"/>
    </wsdl:port>
</wsdl:service>
```

### CODE REVIEW

**Comment by shumonsharif** [comment]
@famod I am pushing this one through for now, so I can get a new release out.  But please feel to review the updates at your convenience and let me know if anything catches your eye, we can always revisit the code as needed!

**Comment by famod** [comment]
I'm having a look later or tomorrow.
Btw, I want to silence some INFO logs but I haven't found the time to do so yet. But I guess that'll have to wait for the next release then.

File: runtime/src/main/java/io/quarkiverse/cxf/transport/VertxHttpServletRequest.java [hunk 1]
```diff
@@ -449,7 +449,9 @@ public String getRequestURI() {
 
     @Override
     public StringBuffer getRequestURL() {
-        return new StringBuffer(request.absoluteURI());
+        String absoluteUri = request.absoluteURI();
+        String urlWithoutParams = absoluteUri.replaceFirst("\\?.*$", "");
```
Comment (famod) [inline runtime/src/main/java/io/quarkiverse/cxf/transport/VertxHttpServletRequest.java:453]: Do we know how often this method is called per "typical" request?
I'm asking because here a thrown-away `Pattern` is created under the hood, so that each invocation will go through a re-compilation the `Pattern`.
I think the `Pattern` should be pre-compiled once (as a constant).

Comment (shumonsharif) [reply runtime/src/main/java/io/quarkiverse/cxf/transport/VertxHttpServletRequest.java:453]: Nice catch Falko!  Each request invocation will have a call to this method, so you're quite right, there will be a performance hit here.  I think we can do a "0.13.1" release with your logging updates and this change?

Comment (famod) [reply runtime/src/main/java/io/quarkiverse/cxf/transport/VertxHttpServletRequest.java:453]: Sounds good! I'll have a look at the logging stuff tomorrow.

Comment (shumonsharif) [reply runtime/src/main/java/io/quarkiverse/cxf/transport/VertxHttpServletRequest.java:453]: Sounds good, thanks.  New PR submitted:  https://github.com/quarkiverse/quarkus-cxf/pull/351
